apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: ui-service
spec:
  selector:
    app: ui-service
  ports:
    - protocol: "TCP"
      port: 3000 # The port that the service is running on in the cluster
      targetPort: 3000 # The port exposed by the service
  type: LoadBalancer
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ui-service
  name: ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ui-service
    spec:
      containers:
        - image: ashishdocker0/eis-ui:2.0
          name: ui-service
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_APIGEE_URL
              valueFrom:
                configMapKeyRef:
                  name: react-config-map
                  key: apigee-url
            